"""Expand tenant/lease, add lease_document

Revision ID: 372d3ee800cf
Revises: 92684f23d422
Create Date: 2026-06-19 02:59:51.908522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '372d3ee800cf'
down_revision: Union[str, None] = '92684f23d422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lease_document',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=False),
    sa.Column('extraction_confidence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extraction_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['lease.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lease_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lease_document_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_document_lease_id'), ['lease_id'], unique=False)

    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('renewal_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('payment_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('returned_check_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('deposit_held_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('deposit_interest_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('utilities_included', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('utilities_tenant_responsibility', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('occupancy_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pets_allowed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pet_restrictions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('pet_deposit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pet_monthly_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('parking_included', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('parking_spaces', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parking_additional_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('no_smoking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('no_waterbeds', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quiet_hours', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('lawn_maintenance_responsibility', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('trash_service_included', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('early_termination_allowed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('early_termination_penalty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('early_termination_notice_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('special_conditions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact_relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('drivers_license', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('ssn_or_tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('employer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('employer_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('annual_income', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reference_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('reference_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('reference_relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('reference_relationship')
        batch_op.drop_column('reference_phone')
        batch_op.drop_column('reference_name')
        batch_op.drop_column('annual_income')
        batch_op.drop_column('job_title')
        batch_op.drop_column('employer_phone')
        batch_op.drop_column('employer_name')
        batch_op.drop_column('ssn_or_tax_id')
        batch_op.drop_column('drivers_license')
        batch_op.drop_column('emergency_contact_relationship')

    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.drop_column('special_conditions')
        batch_op.drop_column('early_termination_notice_days')
        batch_op.drop_column('early_termination_penalty')
        batch_op.drop_column('early_termination_allowed')
        batch_op.drop_column('trash_service_included')
        batch_op.drop_column('lawn_maintenance_responsibility')
        batch_op.drop_column('quiet_hours')
        batch_op.drop_column('no_waterbeds')
        batch_op.drop_column('no_smoking')
        batch_op.drop_column('parking_additional_fee')
        batch_op.drop_column('parking_spaces')
        batch_op.drop_column('parking_included')
        batch_op.drop_column('pet_monthly_fee')
        batch_op.drop_column('pet_deposit')
        batch_op.drop_column('pet_restrictions')
        batch_op.drop_column('pets_allowed')
        batch_op.drop_column('occupancy_limit')
        batch_op.drop_column('utilities_tenant_responsibility')
        batch_op.drop_column('utilities_included')
        batch_op.drop_column('deposit_interest_rate')
        batch_op.drop_column('deposit_held_location')
        batch_op.drop_column('returned_check_fee')
        batch_op.drop_column('payment_frequency')
        batch_op.drop_column('renewal_terms')
        batch_op.drop_column('lease_type')

    with op.batch_alter_table('lease_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lease_document_lease_id'))
        batch_op.drop_index(batch_op.f('ix_lease_document_id'))

    op.drop_table('lease_document')
    # ### end Alembic commands ###
