"""Initial schema

Revision ID: 3de3ef56c782
Revises: 
Create Date: 2026-06-18 18:44:26.297507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3de3ef56c782'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdiction',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('state_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notice_days_month_to_month', sa.Integer(), nullable=False),
    sa.Column('notice_days_lease_termination', sa.Integer(), nullable=False),
    sa.Column('security_deposit_max_months', sa.Float(), nullable=True),
    sa.Column('security_deposit_return_days', sa.Integer(), nullable=True),
    sa.Column('landlord_must_mitigate', sa.Boolean(), nullable=False),
    sa.Column('early_termination_rules', sa.JSON(), nullable=False),
    sa.Column('statute_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jurisdiction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jurisdiction_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdiction_state_code'), ['state_code'], unique=True)

    op.create_table('management_company',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_line1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_line2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('management_company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_management_company_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_management_company_name'), ['name'], unique=False)

    op.create_table('owner',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_line1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_line2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_entity', sa.Boolean(), nullable=False),
    sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_owner_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_owner_name'), ['name'], unique=False)

    op.create_table('tenant',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_of_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_line1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_line2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_last_name'), ['last_name'], unique=False)

    op.create_table('lease_template',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jurisdiction_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('context_schema', sa.JSON(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdiction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lease_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lease_template_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_template_jurisdiction_id'), ['jurisdiction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_template_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_template_template_type'), ['template_type'], unique=False)

    op.create_table('property',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('property_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_line1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_line2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('management_company_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('jurisdiction_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('square_feet', sa.Integer(), nullable=True),
    sa.Column('hoa_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdiction.id'], ),
    sa.ForeignKeyConstraint(['management_company_id'], ['management_company.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_jurisdiction_id'), ['jurisdiction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_management_company_id'), ['management_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_state'), ['state'], unique=False)

    op.create_table('unit',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('property_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('unit_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('square_feet', sa.Integer(), nullable=True),
    sa.Column('market_rent', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_property_id'), ['property_id'], unique=False)

    op.create_table('expense',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('property_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('unit_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('incurred_date', sa.Date(), nullable=False),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receipt_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_incurred_date'), ['incurred_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_unit_id'), ['unit_id'], unique=False)

    op.create_table('lease',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unit_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('property_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('monthly_rent', sa.Float(), nullable=False),
    sa.Column('security_deposit', sa.Float(), nullable=False),
    sa.Column('late_fee', sa.Float(), nullable=False),
    sa.Column('rent_due_day', sa.Integer(), nullable=False),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('docusign_envelope_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lease_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_unit_id'), ['unit_id'], unique=False)

    op.create_table('lease_break_request',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('desired_move_out_date', sa.Date(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('selected_option_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('calculation_context', sa.JSON(), nullable=False),
    sa.Column('docusign_envelope_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['lease.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['lease_break_option.id'], name='fk_lease_break_request_selected_option', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lease_break_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lease_break_request_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_break_request_lease_id'), ['lease_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_break_request_status'), ['status'], unique=False)

    op.create_table('lease_tenant',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_guarantor', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['lease.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lease_tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lease_tenant_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_tenant_lease_id'), ['lease_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_tenant_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('payment',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('payment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['lease.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_lease_id'), ['lease_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_status'), ['status'], unique=False)

    op.create_table('email_approval',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_break_request_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_emails', sa.JSON(), nullable=False),
    sa.Column('cc_emails', sa.JSON(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_html', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['lease_break_request_id'], ['lease_break_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_approval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_approval_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_approval_lease_break_request_id'), ['lease_break_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_approval_status'), ['status'], unique=False)

    op.create_table('lease_break_document',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_break_request_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('template_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rendered_html', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('docusign_envelope_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lease_break_request_id'], ['lease_break_request.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['lease_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lease_break_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lease_break_document_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_break_document_lease_break_request_id'), ['lease_break_request_id'], unique=False)

    op.create_table('lease_break_option',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_break_request_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('option_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_cost_to_tenant', sa.Float(), nullable=False),
    sa.Column('months_charged', sa.Float(), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.Column('is_compliant', sa.Boolean(), nullable=False),
    sa.Column('compliance_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lease_break_request_id'], ['lease_break_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lease_break_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lease_break_option_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_break_option_lease_break_request_id'), ['lease_break_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lease_break_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lease_break_option_lease_break_request_id'))
        batch_op.drop_index(batch_op.f('ix_lease_break_option_id'))

    op.drop_table('lease_break_option')
    with op.batch_alter_table('lease_break_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lease_break_document_lease_break_request_id'))
        batch_op.drop_index(batch_op.f('ix_lease_break_document_id'))

    op.drop_table('lease_break_document')
    with op.batch_alter_table('email_approval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_approval_status'))
        batch_op.drop_index(batch_op.f('ix_email_approval_lease_break_request_id'))
        batch_op.drop_index(batch_op.f('ix_email_approval_id'))

    op.drop_table('email_approval')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_status'))
        batch_op.drop_index(batch_op.f('ix_payment_lease_id'))
        batch_op.drop_index(batch_op.f('ix_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_due_date'))

    op.drop_table('payment')
    with op.batch_alter_table('lease_tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lease_tenant_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_lease_tenant_lease_id'))
        batch_op.drop_index(batch_op.f('ix_lease_tenant_id'))

    op.drop_table('lease_tenant')
    with op.batch_alter_table('lease_break_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lease_break_request_status'))
        batch_op.drop_index(batch_op.f('ix_lease_break_request_lease_id'))
        batch_op.drop_index(batch_op.f('ix_lease_break_request_id'))

    op.drop_table('lease_break_request')
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lease_unit_id'))
        batch_op.drop_index(batch_op.f('ix_lease_status'))
        batch_op.drop_index(batch_op.f('ix_lease_property_id'))
        batch_op.drop_index(batch_op.f('ix_lease_id'))

    op.drop_table('lease')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_unit_id'))
        batch_op.drop_index(batch_op.f('ix_expense_property_id'))
        batch_op.drop_index(batch_op.f('ix_expense_incurred_date'))
        batch_op.drop_index(batch_op.f('ix_expense_id'))

    op.drop_table('expense')
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_property_id'))
        batch_op.drop_index(batch_op.f('ix_unit_id'))

    op.drop_table('unit')
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_state'))
        batch_op.drop_index(batch_op.f('ix_property_owner_id'))
        batch_op.drop_index(batch_op.f('ix_property_name'))
        batch_op.drop_index(batch_op.f('ix_property_management_company_id'))
        batch_op.drop_index(batch_op.f('ix_property_jurisdiction_id'))
        batch_op.drop_index(batch_op.f('ix_property_id'))

    op.drop_table('property')
    with op.batch_alter_table('lease_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lease_template_template_type'))
        batch_op.drop_index(batch_op.f('ix_lease_template_name'))
        batch_op.drop_index(batch_op.f('ix_lease_template_jurisdiction_id'))
        batch_op.drop_index(batch_op.f('ix_lease_template_id'))

    op.drop_table('lease_template')
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_last_name'))
        batch_op.drop_index(batch_op.f('ix_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_email'))

    op.drop_table('tenant')
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_name'))
        batch_op.drop_index(batch_op.f('ix_owner_id'))
        batch_op.drop_index(batch_op.f('ix_owner_email'))

    op.drop_table('owner')
    with op.batch_alter_table('management_company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_management_company_name'))
        batch_op.drop_index(batch_op.f('ix_management_company_id'))

    op.drop_table('management_company')
    with op.batch_alter_table('jurisdiction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jurisdiction_state_code'))
        batch_op.drop_index(batch_op.f('ix_jurisdiction_id'))

    op.drop_table('jurisdiction')
    # ### end Alembic commands ###
