"""Lease break buyout financials

Revision ID: 6325c84c8a6b
Revises: 3863b4e9f70c
Create Date: 2026-06-19 13:54:08.922948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6325c84c8a6b'
down_revision: Union[str, None] = '3863b4e9f70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lease_break_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.LargeBinary(), nullable=True))

    with op.batch_alter_table('lease_break_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('buyout_multiple', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monthly_rent_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_months_rent_held', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_month_rent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('buyout_amount_gross', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_month_credit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cash_due_at_signing', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_cash_collected', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('security_deposit_held', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('security_deposit_refundable', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('move_out_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('final_rent_due_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('selected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('selected_by_tenant', sqlmodel.sql.sqltypes.GUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lease_break_option', schema=None) as batch_op:
        batch_op.drop_column('selected_by_tenant')
        batch_op.drop_column('selected_at')
        batch_op.drop_column('terms')
        batch_op.drop_column('final_rent_due_date')
        batch_op.drop_column('move_out_date')
        batch_op.drop_column('security_deposit_refundable')
        batch_op.drop_column('security_deposit_held')
        batch_op.drop_column('total_cash_collected')
        batch_op.drop_column('cash_due_at_signing')
        batch_op.drop_column('last_month_credit')
        batch_op.drop_column('buyout_amount_gross')
        batch_op.drop_column('current_month_rent')
        batch_op.drop_column('last_months_rent_held')
        batch_op.drop_column('monthly_rent_amount')
        batch_op.drop_column('buyout_multiple')
        batch_op.drop_column('option_number')

    with op.batch_alter_table('lease_break_document', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('file_type')

    # ### end Alembic commands ###
