"""Add HOA and HOA documents

Revision ID: 92684f23d422
Revises: 3de3ef56c782
Create Date: 2026-06-19 02:15:55.364372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '92684f23d422'
down_revision: Union[str, None] = '3de3ef56c782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hoa',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('management_company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_line1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_line2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dues_amount', sa.Float(), nullable=True),
    sa.Column('dues_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hoa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hoa_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hoa_name'), ['name'], unique=False)

    op.create_table('hoa_document',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hoa_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hoa_id'], ['hoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hoa_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hoa_document_hoa_id'), ['hoa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hoa_document_id'), ['id'], unique=False)

    with op.batch_alter_table('lease_break_request', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_lease_break_request_selected_option', 'lease_break_option', ['selected_option_id'], ['id'], use_alter=True)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hoa_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_property_hoa_id'), ['hoa_id'], unique=False)
        batch_op.create_foreign_key(None, 'hoa', ['hoa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_property_hoa_id'))
        batch_op.drop_column('hoa_id')

    with op.batch_alter_table('lease_break_request', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lease_break_request_selected_option', type_='foreignkey')

    with op.batch_alter_table('hoa_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hoa_document_id'))
        batch_op.drop_index(batch_op.f('ix_hoa_document_hoa_id'))

    op.drop_table('hoa_document')
    with op.batch_alter_table('hoa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hoa_name'))
        batch_op.drop_index(batch_op.f('ix_hoa_id'))

    op.drop_table('hoa')
    # ### end Alembic commands ###
