"""Add property_photo

Revision ID: fdf337a8f3a8
Revises: 372d3ee800cf
Create Date: 2026-06-19 12:13:44.398145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fdf337a8f3a8'
down_revision: Union[str, None] = '372d3ee800cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_photo',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('property_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_photo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_photo_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_photo_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_photo_property_id'))
        batch_op.drop_index(batch_op.f('ix_property_photo_id'))

    op.drop_table('property_photo')
    # ### end Alembic commands ###
