import { useEffect, useState } from 'react';
import { emailApprovalAPI, getErrorMessage } from '../services/api';
import type { EmailApproval } from '../types';
import { Card, EmptyState, PageHeader, Spinner } from '../components/ui';
import { StatusBadge } from '../components/StatusBadge';

export const ApprovalsPage = () => {
  const [data, setData] = useState<EmailApproval[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [unavailable, setUnavailable] = useState(false);

  useEffect(() => {
    emailApprovalAPI
      .list()
      .then(setData)
      .catch((err) => {
        // The email-approvals endpoint isn't implemented yet (backend M5-6).
        getErrorMessage(err);
        setUnavailable(true);
      })
      .finally(() => setLoading(false));
  }, []);

  return (
    <div>
      <PageHeader title="Approvals" subtitle="Emails awaiting your review before sending" />

      {loading && <Spinner />}

      {!loading && unavailable && (
        <Card className="p-8 text-center text-gray-500">
          <p className="font-medium text-gray-700">Approvals queue not available yet</p>
          <p className="text-sm mt-1">
            The email-approval endpoints ship with backend Milestones 5–6. Draft emails generated by
            the lease-break workflow will appear here for review.
          </p>
        </Card>
      )}

      {!loading && !unavailable && data && data.length === 0 && (
        <EmptyState title="No pending approvals" hint="You're all caught up." />
      )}

      {!loading && !unavailable && data && data.length > 0 && (
        <div className="space-y-3">
          {data.map((e) => (
            <Card key={e.id} className="p-5 flex items-center justify-between">
              <div>
                <p className="font-medium text-gray-900">{e.subject}</p>
                <p className="text-sm text-gray-500">To: {e.to_emails.join(', ')}</p>
              </div>
              <StatusBadge status={e.status} variant={e.status === 'draft' ? 'yellow' : 'blue'} />
            </Card>
          ))}
        </div>
      )}
    </div>
  );
};
